### ISSUE TITLE
new zoom icons

### ISSUE THREAD

**Issue by arojascastro** [Chafalleiro/OpenseaDragonDZO#12]
Hi there, 
I made some blue zoom icons that I might like to share but I failed to submit them.

Thanks

![zoomout_rest](https://cloud.githubusercontent.com/assets/7340111/19416370/66944f96-938f-11e6-9371-0910b25f5f6d.png)
![zoomout_pressed](https://cloud.githubusercontent.com/assets/7340111/19416371/66a7ef2e-938f-11e6-8fa9-4f0395486a36.png)
![zoomout_hover](https://cloud.githubusercontent.com/assets/7340111/19416372/66a84654-938f-11e6-9d5b-28ef2c4fd222.png)
![zoomout_grouphover](https://cloud.githubusercontent.com/assets/7340111/19416373/66a9107a-938f-11e6-9b8f-33fff735963f.png)
![zoomin_rest](https://cloud.githubusercontent.com/assets/7340111/19416374/66a9fb16-938f-11e6-95aa-04f18b0b4aba.png)
![zoomin_grouphover](https://cloud.githubusercontent.com/assets/7340111/19416386/6750e03e-938f-11e6-8d6c-41f321ecd2a6.png)
![zoomin_hover](https://cloud.githubusercontent.com/assets/7340111/19416375/66bc6166-938f-11e6-9b40-58df1768653f.png)
![zoomin_pressed](https://cloud.githubusercontent.com/assets/7340111/19416376/66d0901e-938f-11e6-9558-dde2ba6b35c7.png)
![rotateright_rest](https://cloud.githubusercontent.com/assets/7340111/19416377/66e59414-938f-11e6-9775-9aa4963a8e33.png)
![rotateright_grouphover](https://cloud.githubusercontent.com/assets/7340111/19416379/66f95c56-938f-11e6-9fef-aedf9f773aab.png)
![rotateright_hover](https://cloud.githubusercontent.com/assets/7340111/19416378/66f72dc8-938f-11e6-9637-4d093dd7aea8.png)
![rotateright_pressed](https://cloud.githubusercontent.com/assets/7340111/19416380/66fb56be-938f-11e6-89b8-004b5ce81604.png)
![rotateleft_rest](https://cloud.githubusercontent.com/assets/7340111/19416381/66ff3ed2-938f-11e6-9879-56161026b5d1.png)
![rotateleft_grouphover](https://cloud.githubusercontent.com/assets/7340111/19416382/6722c474-938f-11e6-8c5f-9926f41dd83e.png)
![rotateleft_hover](https://cloud.githubusercontent.com/assets/7340111/19416383/6736814e-938f-11e6-9f04-0e10de4f95aa.png)
![rotateleft_pressed](https://cloud.githubusercontent.com/assets/7340111/19416384/673b33f6-938f-11e6-8cf7-055e1c9212a2.png)
![home_rest](https://cloud.githubusercontent.com/assets/7340111/19416385/673e15ee-938f-11e6-9b04-7182eed1bfe8.png)
![home_grouphover](https://cloud.githubusercontent.com/assets/7340111/19416388/675701ee-938f-11e6-98ba-2e3f346dc367.png)
![home_hover](https://cloud.githubusercontent.com/assets/7340111/19416387/6754bd3a-938f-11e6-9959-59f305a06286.png)
![home_pressed](https://cloud.githubusercontent.com/assets/7340111/19416389/676c7204-938f-11e6-9e60-a5721ff83c80.png)
![fullpage_rest](https://cloud.githubusercontent.com/assets/7340111/19416391/679e346a-938f-11e6-8920-246cfa2d3a31.png)
![fullpage_grouphover](https://cloud.githubusercontent.com/assets/7340111/19416390/679c3b6a-938f-11e6-9edd-2c3ed46eb2d3.png)
![fullpage_hover](https://cloud.githubusercontent.com/assets/7340111/19416393/67a025c2-938f-11e6-85cb-f6c8be99bd59.png)
![fullpage_pressed](https://cloud.githubusercontent.com/assets/7340111/19416392/679e5594-938f-11e6-88d2-0deda10ec36f.png)

**Comment by Chafalleiro** [comment]
Thanks for the info :)
